stages:
  - build
  - deploy

before_script:
  - chmod +x ./BackEnd/mvnw

build-server:
  stage: build
  script: 
  - cd ./BackEnd
  - mvn package
  artifacts:
    paths:
      - target/cyschedule-server.jar

production:
  stage: deploy
  script:
  - rm -rf /opt/cyschedule/*.jar
  - mv target/cyschedule-server.jar /opt/cyschedule/
  - redis-cli FLUSHALL
  only:
  - master