stages:
    - build
    - deploy

before_script:
    ##
    ## create ssh folder
    ##
    - mkdir ~/.ssh
    
    ##
    ## fix "Could not open a connection to your authentication agent."
    ##
    - ssh-agent bash
    
    ##
    ## Add ssh keys and know hosts for scp
    ##
    - ssh-keyscan dev.hanzec.com >> ~/.ssh/known_hosts
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    ##
    ## Set correct file permission for these file
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 644 ~/.ssh/known_hosts

build-server:
  stage: build
  script: 
  - cd ./BackEnd
  - mvn package
  artifacts:
    paths:
      - target/cyschedule-server.jar

deploy-server:
  stage: deploy
  script:
  ##
  ## Copy exec file from runner to production server
  ##
  - scp target/cyschedule-server.jar $$DEPLOY_SSH_USER@$$DEPLOY_SERVER:/opt/cyshedule-server
  
  ##
  ## Login to production server
  ##
  - ssh $$DEPLOY_SSH_USER@$$DEPLOY_SERVER
  - rm -rf /opt/cyschedule/*.jar
  - mv target/cyschedule-server.jar /opt/cyschedule/
  - redis-cli FLUSHALL
  only:
  - master